services:
  robot-base:
    container_name: robot-dev
  #  network_mode: "host"
    ports:
      - "192.168.1.101:50001:50001"
      - "192.168.1.101:50002:50002"
      - "192.168.1.101:50003:50003"
      - "192.168.1.101:50004:50004"
    build:
      context: .
      ssh: 
        - default
    volumes:
      - "./src:/workspaces/ros2_ws/src"
    environment:
      - MAIN_WS=/workspaces/ros2_ws
  windows-wsl-nvidia:
    extends: robot-base
    build:
      target: robot_dev_wsl_nvidia
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/mnt/wslg:/mnt/wslg"
      - "/usr/lib/wsl:/usr/lib/wsl"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
  windows-wsl:
    extends: robot-base
    build:
      target: robot_dev_wsl
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/mnt/wslg:/mnt/wslg"
      - "/usr/lib/wsl:/usr/lib/wsl"
  mac:
    extends: robot-base
    build:
      target: robot_dev_mac
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
  linux:
    extends: robot-base
    build:
      target: robot_dev_linux
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"