services:
  windows:
    container_name: robot-dev
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
      ssh: 
        - default
    volumes:
      - "./src:/workspaces/ros2_ws/src"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/mnt/wslg:/mnt/wslg"
      - "/usr/lib/wsl:/usr/lib/wsl"
    devices:
      - /dev/dxg:/dev/dxg
  mac:
    container_name: robot-dev
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
      ssh: 
        - default
    volumes:
      - "./src:/workspaces/ros2_ws/src"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
  linux:
    container_name: robot-dev
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
      ssh: 
        - default
    volumes:
      - "./src:/workspaces/ros2_ws/src"
environment:
  - MAIN_WS=/workspaces/ros2_ws